### ISSUE TITLE
On a more serious note

### ISSUE THREAD

**Issue by thedumbtechguy** [pyricau/fragnums#13]
Since you state the principles are good and from what I have seen, the code looks solid (just a cursory look).

This looks like a great idea: without the enums of course. 

What are the potential cons you envision?
Thanks.

**Comment by pyricau** [comment]
None, it's just a very simple way of doing things. So for more complex needs, you'll need to add more complexity to handle all cases. But don't worry, it can never be as complex and buggy as fragments.

I would argue that Flow, combined with Mortar and a few classes of your own to adapt to your needs, would do what you need. In fact, I wrote Fragnums by stripping down Flow and a few other things. That's why it looks solid :) .

**Comment by thedumbtechguy** [comment]
I just thought I'd bring to your attention a library I'm writing using inspiration from this lib and another called Pancakes.
We are actually using it in our new app which should go into production really soon.
As at now, it works really well with no issues. 

https://github.com/frostymarvelous/Folio

**Comment by thedumbtechguy** [comment]
Sadly, I am yet to document it.
